version: '3.8'

services:
  sejmbot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_DATE: ${BUILD_DATE:-}
        VERSION: "2.0"

    image: sejmbot:latest
    container_name: sejmbot
    hostname: sejmbot

    # Restart policy
    restart: unless-stopped

    # Environment variables
    environment:
      - TZ=Europe/Warsaw
      - PYTHONUNBUFFERED=1
      - PYTHONOPTIMIZE=1

    # Volumes for persistent data - create local directories
    volumes:
      - ./data/transkrypty:/app/transkrypty
      - ./data/logs:/app/logs

    # Resource limits (adjust for Pi vs Desktop)
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT:-1.0}
          memory: ${MEMORY_LIMIT:-512M}
        reservations:
          cpus: ${CPU_RESERVATION:-0.25}
          memory: ${MEMORY_RESERVATION:-128M}

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Health check - less frequent for Pi
    healthcheck:
      test: ["CMD", "python", "-c", "import sejmbot; print('OK')"]
      interval: ${HEALTH_INTERVAL:-30m}
      timeout: 10s
      retries: 3
      start_period: 30s

    # Labels for management
    labels:
      - "com.docker.compose.project=sejmbot"
      - "description=Parser transkryptów Sejmu RP"
      - "version=2.0"

  # Optional: monitoring with Watchtower (auto-updates)
  watchtower:
    image: containrrr/watchtower:latest
    container_name: sejmbot-watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_POLL_INTERVAL=86400  # Check daily
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: sejmbot
    profiles:
      - monitoring

# Create networks
networks:
  default:
    name: sejmbot-network